openapi: 3.0.1
info:
  title: Text Manipulation Plugin
  description: A plugin that allows for exact text manipulation. The text manipulations are string reversals and adding three dots between every third charachter.
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /reverse:
    put:
      operationId: reverseText
      summary: Reverses the order of the characters in a string
      parameters:
      - in: path
        name: text
        schema:
            type: string
        required: true
        description: The text to be reversed. 
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getReverseTextResponse'
  /dots:
    put:
      operationId: addDots
      summary: Adds three dots between every third charachter in a string
      parameters:
      - in: path
        name: text
        schema:
            type: string
        required: true
        description: The text to be manipulated.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getAddDotsResponse'
components:
  schemas:
    getTodosResponse:
      type: text
      properties:
        type: string
        description: The reversed text.
    getDotsResponse:
      type: text
      properties:
        type: string
        description: The original text with three dots between every third charachter.